version: "3.7"
services:
    # image project
    api:
        build: 
            args: 
                user: jander
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - app_network
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8989:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - app_network
    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: always
        environment:
            MYSQL_DATABASE: api
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD:  root
            MYSQL_USER:  root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - app_network


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        tty: true
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_USER=default
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
            - MAX_EXECUTION_TIME=300
            - MEMORY_LIMIT=256M
            - UPLOAD_LIMIT=512M
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - app_network
  
networks: 
    app_network:
        driver: bridge